name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0']

    steps:
      - uses: actions/checkout@v2
      - name: Set up php${{ matrix.php-versons }}
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Install dependencies
        run: composer i
      - name: PHPUnit
        run: ./vendor/phpunit/phpunit/phpunit -c tests/phpunit.xml
